<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Model;

use StockOnOrder\Model\Base\StockOnOrderDecreaseOnCreation as BaseStockOnOrderDecreaseOnCreation;

/**
 * Class StockOnOrderDecreaseOnCreation
 * @package StockOnOrder\Model
 */
class StockOnOrderDecreaseOnCreation extends BaseStockOnOrderDecreaseOnCreation
{
}
