<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Model;

use StockOnOrder\Model\Base\StockOnOrder as BaseStockOnOrder;

/**
 * Class StockOnOrder
 * @package StockOnOrder\Model
 */
class StockOnOrder extends BaseStockOnOrder
{
}
