<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Model;

use StockOnOrder\Model\Base\StockOnOrderConfig as BaseStockOnOrderConfig;

/**
 * Class StockOnOrderConfig
 * @package StockOnOrder\Model
 */
class StockOnOrderConfig extends BaseStockOnOrderConfig
{
}
