<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action;

use StockOnOrder\Action\Base\StockOnOrderAction as  BaseStockOnOrderAction;

/**
 * Class StockOnOrderAction
 * @package StockOnOrder\Action
 */
class StockOnOrderAction extends BaseStockOnOrderAction
{
}
