<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action;

use StockOnOrder\Action\Base\StockOnOrderDecreaseOnCreationAction as  BaseStockOnOrderDecreaseOnCreationAction;

/**
 * Class StockOnOrderDecreaseOnCreationAction
 * @package StockOnOrder\Action
 */
class StockOnOrderDecreaseOnCreationAction extends BaseStockOnOrderDecreaseOnCreationAction
{
}
