<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action;

use StockOnOrder\Action\Base\StockOnOrderConfigAction as  BaseStockOnOrderConfigAction;

/**
 * Class StockOnOrderConfigAction
 * @package StockOnOrder\Action
 */
class StockOnOrderConfigAction extends BaseStockOnOrderConfigAction
{
}
