<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Type;

use StockOnOrder\Form\Type\Base\StockOnOrderIdType as BaseStockOnOrderIdType;

/**
 * Class StockOnOrder
 * @package StockOnOrder\Form
 */
class StockOnOrderIdType extends BaseStockOnOrderIdType
{
}
