<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Type;

use StockOnOrder\Form\Type\Base\StockOnOrderConfigIdType as BaseStockOnOrderConfigIdType;

/**
 * Class StockOnOrderConfig
 * @package StockOnOrder\Form
 */
class StockOnOrderConfigIdType extends BaseStockOnOrderConfigIdType
{
}
