<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderEvent as BaseStockOnOrderEvent;

/**
 * Class StockOnOrderEvent
 * @package StockOnOrder\Event
 */
class StockOnOrderEvent extends BaseStockOnOrderEvent
{
}
