<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderDecreaseOnCreationEvent as BaseStockOnOrderDecreaseOnCreationEvent;

/**
 * Class StockOnOrderDecreaseOnCreationEvent
 * @package StockOnOrder\Event
 */
class StockOnOrderDecreaseOnCreationEvent extends BaseStockOnOrderDecreaseOnCreationEvent
{
}
