<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderDecreaseOnCreationEvents as BaseStockOnOrderDecreaseOnCreationEvents;

/**
 * Class StockOnOrderDecreaseOnCreationEvents
 * @package StockOnOrder\Event
 */
class StockOnOrderDecreaseOnCreationEvents extends BaseStockOnOrderDecreaseOnCreationEvents
{
}
