<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderConfigEvents as BaseStockOnOrderConfigEvents;

/**
 * Class StockOnOrderConfigEvents
 * @package StockOnOrder\Event
 */
class StockOnOrderConfigEvents extends BaseStockOnOrderConfigEvents
{
}
