<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderEvents as BaseStockOnOrderEvents;

/**
 * Class StockOnOrderEvents
 * @package StockOnOrder\Event
 */
class StockOnOrderEvents extends BaseStockOnOrderEvents
{
}
