<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event;

use StockOnOrder\Event\Base\StockOnOrderConfigEvent as BaseStockOnOrderConfigEvent;

/**
 * Class StockOnOrderConfigEvent
 * @package StockOnOrder\Event
 */
class StockOnOrderConfigEvent extends BaseStockOnOrderConfigEvent
{
}
