<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Base;

use StockOnOrder\Form\StockOnOrderConfigCreateForm as ChildStockOnOrderConfigCreateForm;
use StockOnOrder\Form\Type\StockOnOrderConfigIdType;

/**
 * Class StockOnOrderConfigForm
 * @package StockOnOrder\Form
 * @author TheliaStudio
 */
class StockOnOrderConfigUpdateForm extends ChildStockOnOrderConfigCreateForm
{
    const FORM_NAME = "stock_on_order_config_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", StockOnOrderConfigIdType::TYPE_NAME)
        ;
    }
}
