<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Base;

use StockOnOrder\StockOnOrder;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class StockOnOrderConfigCreateForm
 * @package StockOnOrder\Form\Base
 * @author TheliaStudio
 */
class StockOnOrderConfigCreateForm extends BaseForm
{
    const FORM_NAME = "stock_on_order_config_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addModuleIdField($translationKeys, $fieldsIdKeys);
        $this->addStatusIdField($translationKeys, $fieldsIdKeys);
        $this->addBehaviorField($translationKeys, $fieldsIdKeys);
    }

    protected function addModuleIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("module_id", IntegerType::class, array(
            "label" => $this->translator->trans($this->readKey("module_id", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("module_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addStatusIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("status_id", IntegerType::class, array(
            "label" => $this->translator->trans($this->readKey("status_id", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("status_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addBehaviorField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("behavior", TextType::class, array(
            "label" => $this->translator->trans($this->readKey("behavior", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("behavior", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public static function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "module_id" => "stock_on_order_config_module_id",
            "status_id" => "stock_on_order_config_status_id",
            "behavior" => "stock_on_order_config_behavior",
        );
    }
}
