<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Base;

use StockOnOrder\StockOnOrder;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class StockOnOrderDecreaseOnCreationCreateForm
 * @package StockOnOrder\Form\Base
 * @author TheliaStudio
 */
class StockOnOrderDecreaseOnCreationCreateForm extends BaseForm
{
    const FORM_NAME = "stock_on_order_decrease_on_creation_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addModuleIdField($translationKeys, $fieldsIdKeys);
        $this->addDecreaseOnOrderCreationField($translationKeys, $fieldsIdKeys);
    }

    protected function addModuleIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("module_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("module_id", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("module_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addDecreaseOnOrderCreationField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("decrease_on_order_creation", "checkbox", array(
            "label" => $this->translator->trans($this->readKey("decrease_on_order_creation", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("decrease_on_order_creation", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "module_id" => "stock_on_order_decrease_on_creation_module_id",
            "decrease_on_order_creation" => "stock_on_order_decrease_on_creation_decrease_on_order_creation",
        );
    }
}
