<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Base;

use StockOnOrder\StockOnOrder;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class StockOnOrderCreateForm
 * @package StockOnOrder\Form\Base
 * @author TheliaStudio
 */
class StockOnOrderCreateForm extends BaseForm
{
    const FORM_NAME = "stock_on_order_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addOrderIdField($translationKeys, $fieldsIdKeys);
        $this->addIsStockDecreasedField($translationKeys, $fieldsIdKeys);
    }

    protected function addOrderIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("order_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("order_id", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("order_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addIsStockDecreasedField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("is_stock_decreased", "checkbox", array(
            "label" => $this->translator->trans($this->readKey("is_stock_decreased", $translationKeys), [], StockOnOrder::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("is_stock_decreased", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "order_id" => "stock_on_order_order_id",
            "is_stock_decreased" => "stock_on_order_is_stock_decreased",
        );
    }
}
