<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Loop;

use StockOnOrder\Loop\Base\StockOnOrderDecreaseOnCreation as BaseStockOnOrderDecreaseOnCreationLoop;

/**
 * Class StockOnOrderDecreaseOnCreation
 * @package StockOnOrder\Loop
 */
class StockOnOrderDecreaseOnCreation extends BaseStockOnOrderDecreaseOnCreationLoop
{
    /**
     * You may now add your own logic
     */
}
