<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Loop;

use StockOnOrder\Loop\Base\StockOnOrder as BaseStockOnOrderLoop;

/**
 * Class StockOnOrder
 * @package StockOnOrder\Loop
 */
class StockOnOrder extends BaseStockOnOrderLoop
{
    /**
     * You may now add your own logic
     */
}
