<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Loop;

use StockOnOrder\Loop\Base\StockOnOrderConfig as BaseStockOnOrderConfigLoop;

/**
 * Class StockOnOrderConfig
 * @package StockOnOrder\Loop
 */
class StockOnOrderConfig extends BaseStockOnOrderConfigLoop
{
    /**
     * You may now add your own logic
     */
}
