<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderDecreaseOnCreationUpdateForm as BaseStockOnOrderDecreaseOnCreationUpdateForm;

/**
 * Class StockOnOrderDecreaseOnCreationUpdateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderDecreaseOnCreationUpdateForm extends BaseStockOnOrderDecreaseOnCreationUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "module_id" => "module_id",
            "decreased_on_order_creation" => "decreased_on_order_creation",
        );
    }
}
