<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderDecreaseOnCreationCreateForm as BaseStockOnOrderDecreaseOnCreationCreateForm;

/**
 * Class StockOnOrderDecreaseOnCreationCreateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderDecreaseOnCreationCreateForm extends BaseStockOnOrderDecreaseOnCreationCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "module_id" => "Module id",
            "decreased_on_order_creation" => "Decrease stock on order creation",
        );
    }
}
