<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderConfigCreateForm as BaseStockOnOrderConfigCreateForm;

/**
 * Class StockOnOrderConfigCreateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderConfigCreateForm extends BaseStockOnOrderConfigCreateForm
{
    public static function getName(): string
    {
        return 'stock_on_order_config.create';
    }

    public function getTranslationKeys(): array
    {
        return array(
            "module_id" => "Module id",
            "status_id" => "Status id",
            "behavior" => "Behavior",
        );
    }
}
