<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderUpdateForm as BaseStockOnOrderUpdateForm;

/**
 * Class StockOnOrderUpdateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderUpdateForm extends BaseStockOnOrderUpdateForm
{
    public static function getName(): string
    {
        return 'stock_on_order.update';
    }

    public function getTranslationKeys(): array
    {
        return array(
            "order_id" => "order_id",
            "isStockDecreased" => "isStockDecreased",
        );
    }
}
