<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderConfigUpdateForm as BaseStockOnOrderConfigUpdateForm;

/**
 * Class StockOnOrderConfigUpdateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderConfigUpdateForm extends BaseStockOnOrderConfigUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "module_id" => "module_id",
            "status_id" => "status_id",
            "behavior" => "behavior",
        );
    }
}
