<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderCreateForm as BaseStockOnOrderCreateForm;

/**
 * Class StockOnOrderCreateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderCreateForm extends BaseStockOnOrderCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "order_id" => "Order id",
            "isStockDecreased" => "IsStockDecreased",
        );
    }
}
