<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form;

use StockOnOrder\Form\Base\StockOnOrderDecreaseOnCreationUpdateForm as BaseStockOnOrderDecreaseOnCreationUpdateForm;

/**
 * Class StockOnOrderDecreaseOnCreationUpdateForm
 * @package StockOnOrder\Form
 */
class StockOnOrderDecreaseOnCreationUpdateForm extends BaseStockOnOrderDecreaseOnCreationUpdateForm
{
    public static function getName(): string
    {
        return 'stock_on_order_decrease_on_creation.update';
    }

    public function getTranslationKeys(): array
    {
        return array(
            "id" => "id",
            "module_id" => "module_id",
            "decrease_on_order_creation" => "decrease_on_order_creation",
        );
    }
}
