<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use StockOnOrder\Model\StockOnOrderQuery;

/**
 * Class StockOnOrder
 * @package StockOnOrder\Loop\Base
 * @author TheliaStudio
 */
class StockOnOrder extends BaseLoop implements PropelSearchLoopInterface
{

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \StockOnOrder\Model\StockOnOrder $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ORDER_ID", $entry->getOrderId())
                ->set("IS_STOCK_DECREASED", $entry->getIsStockDecreased())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("order_id"),
            Argument::createBooleanOrBothTypeArgument("is_stock_decreased", BooleanOrBothType::ANY),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "order_id",
                    "order_id-reverse",
                    "is_stock_decreased",
                    "is_stock_decreased-reverse",
                ],
                "id"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new StockOnOrderQuery();

        if (null !== $order_id = $this->getOrderId()) {
            $query->filterByOrderId($order_id);
        }

        if (BooleanOrBothType::ANY !== $is_stock_decreased = $this->getIsStockDecreased()) {
            $query->filterByIsStockDecreased($is_stock_decreased);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "order_id":
                    $query->orderByOrderId();
                    break;
                case "order_id-reverse":
                    $query->orderByOrderId(Criteria::DESC);
                    break;
                case "is_stock_decreased":
                    $query->orderByIsStockDecreased();
                    break;
                case "is_stock_decreased-reverse":
                    $query->orderByIsStockDecreased(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
