<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use StockOnOrder\Model\StockOnOrderDecreaseOnCreationQuery;

/**
 * Class StockOnOrderDecreaseOnCreation
 * @package StockOnOrder\Loop\Base
 * @author TheliaStudio
 */
class StockOnOrderDecreaseOnCreation extends BaseLoop implements PropelSearchLoopInterface
{
    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \StockOnOrder\Model\StockOnOrderDecreaseOnCreation $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ID", $entry->getId())
                ->set("MODULE_ID", $entry->getModuleId())
                ->set("DECREASE_ON_ORDER_CREATION", $entry->getDecreaseOnOrderCreation())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("id"),
            Argument::createIntListTypeArgument("module_id"),
            Argument::createBooleanOrBothTypeArgument("decrease_on_order_creation", BooleanOrBothType::ANY),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "id",
                    "id-reverse",
                    "module_id",
                    "module_id-reverse",
                    "decrease_on_order_creation",
                    "decrease_on_order_creation-reverse",
                ],
                "id"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new StockOnOrderDecreaseOnCreationQuery();

        if (null !== $id = $this->getId()) {
            $query->filterById($id);
        }

        if (null !== $module_id = $this->getModuleId()) {
            $query->filterByModuleId($module_id);
        }

        if (BooleanOrBothType::ANY !== $decrease_on_order_creation = $this->getDecreaseOnOrderCreation()) {
            $query->filterByDecreaseOnOrderCreation($decrease_on_order_creation);
        }

        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "id":
                    $query->orderById();
                    break;
                case "id-reverse":
                    $query->orderById(Criteria::DESC);
                    break;
                case "module_id":
                    $query->orderByModuleId();
                    break;
                case "module_id-reverse":
                    $query->orderByModuleId(Criteria::DESC);
                    break;
                case "decrease_on_order_creation":
                    $query->orderByDecreaseOnOrderCreation();
                    break;
                case "decrease_on_order_creation-reverse":
                    $query->orderByDecreaseOnOrderCreation(Criteria::DESC);
                    break;
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
