<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event\Module;

use StockOnOrder\Event\Module\Base\StockOnOrderEvents as BaseStockOnOrderEvents;

/**
 * Class StockOnOrderEvents
 * @package StockOnOrder\Event\Module
 * @author TheliaStudio
 */
class StockOnOrderEvents extends BaseStockOnOrderEvents
{
}
