<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Controller\Base;

use Propel\Runtime\ActiveRecord\ActiveRecordInterface;
use Propel\Runtime\Event\ActiveRecordEvent;
use StockOnOrder\Event\Base\StockOnOrderEvents as StockOnOrderEventsAlias;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Event\ActionEvent;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Core\Template\ParserContext;
use Thelia\Form\BaseForm;
use Thelia\Tools\URL;
use StockOnOrder\Event\StockOnOrderEvent;
use StockOnOrder\Model\StockOnOrderQuery;

/**
 * Class StockOnOrderController
 * @package StockOnOrder\Controller\Base
 * @author TheliaStudio
 */
class StockOnOrderController extends AbstractCrudController
{
    public RequestStack $requestStack;
    public ParserContext $parserContext;

    public function __construct(RequestStack $requestStack, ParserContext $parserContext)
    {
        $this->requestStack = $requestStack;
        $this->parserContext = $parserContext;

        parent::__construct(
            "stock_on_order",
            "id",
            "order",
            AdminResources::MODULE,
            StockOnOrderEventsAlias::CREATE,
            StockOnOrderEventsAlias::UPDATE,
            StockOnOrderEventsAlias::DELETE,
            null,
            null,
            "StockOnOrder"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm(): ?BaseForm
    {
        return $this->createForm("stock_on_order.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array()): ?BaseForm
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("stock_on_order.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm(ParserContext $parserContext, $object): BaseForm
    {
        $data = array(
            "id" => $object->getId(),
            "order_id" => $object->getOrderId(),
            "is_stock_decreased" => (bool) $object->getIsStockDecreased(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return ActionEvent|ActiveRecordEvent|null
     */
    protected function getCreationEvent($formData): ActionEvent|ActiveRecordEvent|null
    {
        $event = new StockOnOrderEvent();

        $event->setOrderId($formData["order_id"]);
        $event->setIsStockDecreased($formData["is_stock_decreased"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return ActionEvent|ActiveRecordEvent|null
     */
    protected function getUpdateEvent($formData): ActionEvent|ActiveRecordEvent|null
    {
        $event = new StockOnOrderEvent();

        $event->setId($formData["id"]);
        $event->setOrderId($formData["order_id"]);
        $event->setIsStockDecreased($formData["is_stock_decreased"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent(): ActionEvent|ActiveRecordEvent|null
    {
        $event = new StockOnOrderEvent();

        $event->setId($this->requestStack->getCurrentRequest()->request->get("stock_on_order_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event): bool
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event): mixed
    {
        return $event->getStockOnOrder();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject(): ?ActiveRecordInterface
    {
        return StockOnOrderQuery::create()
            ->findPk($this->requestStack->getCurrentRequest()->query->get("stock_on_order_id"))
        ;
    }

    /**
     * Returns the object label from the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object): ?string
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object): int
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder): Response
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("stock-on-orders");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate(): Response
    {
        $this->parserContext
            ->set(
                "stock_on_order_id",
                $this->requestStack->getCurrentRequest()->query->get("stock_on_order_id")
            )
        ;

        return $this->render("stock-on-order-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return RedirectResponse|Response
     */
    protected function redirectToEditionTemplate(): RedirectResponse|Response
    {
        $id = $this->requestStack->getCurrentRequest()->query->get("stock_on_order_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/StockOnOrder/stock_on_order/edit",
                [
                    "stock_on_order_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return RedirectResponse|Response
     */
    protected function redirectToListTemplate(): RedirectResponse|Response
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/StockOnOrder/stock_on_order")
        );
    }
}
