<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use StockOnOrder\Event\StockOnOrderConfigEvent;
use StockOnOrder\Event\StockOnOrderConfigEvents;
use StockOnOrder\Model\StockOnOrderConfigQuery;

/**
 * Class StockOnOrderConfigController
 * @package StockOnOrder\Controller\Base
 * @author TheliaStudio
 */
class StockOnOrderConfigController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "stock_on_order_config",
            "id",
            "order",
            AdminResources::MODULE,
            StockOnOrderConfigEvents::CREATE,
            StockOnOrderConfigEvents::UPDATE,
            StockOnOrderConfigEvents::DELETE,
            null,
            null,
            "StockOnOrder"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("stock_on_order_config.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("stock_on_order_config.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "module_id" => $object->getModuleId(),
            "status_id" => $object->getStatusId(),
            "behavior" => $object->getBehavior(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new StockOnOrderConfigEvent();

        $event->setModuleId($formData["module_id"]);
        $event->setStatusId($formData["status_id"]);
        $event->setBehavior($formData["behavior"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new StockOnOrderConfigEvent();

        $event->setId($formData["id"]);
        $event->setModuleId($formData["module_id"]);
        $event->setStatusId($formData["status_id"]);
        $event->setBehavior($formData["behavior"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new StockOnOrderConfigEvent();

        $event->setId($this->getRequest()->request->get("stock_on_order_config_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getStockOnOrderConfig();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return StockOnOrderConfigQuery::create()
            ->findPk($this->getRequest()->query->get("stock_on_order_config_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("stock-on-order-configs");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "stock_on_order_config_id",
                $this->getRequest()->query->get("stock_on_order_config_id")
            )
        ;

        return $this->render("stock-on-order-config-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("stock_on_order_config_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/StockOnOrder/stock_on_order_config/edit",
                [
                    "stock_on_order_config_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/StockOnOrder/stock_on_order_config")
        );
    }
}
