<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event\Base;

use Thelia\Core\Event\ActionEvent;
use StockOnOrder\Model\StockOnOrderConfig;

/**
* Class StockOnOrderConfigEvent
* @package StockOnOrder\Event\Base
* @author TheliaStudio
*/
class StockOnOrderConfigEvent extends ActionEvent
{
    protected $id;
    protected $moduleId;
    protected $statusId;
    protected $behavior;
    protected $stockOnOrderConfig;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getModuleId()
    {
        return $this->moduleId;
    }

    public function setModuleId($moduleId)
    {
        $this->moduleId = $moduleId;

        return $this;
    }

    public function getStatusId()
    {
        return $this->statusId;
    }

    public function setStatusId($statusId)
    {
        $this->statusId = $statusId;

        return $this;
    }

    public function getBehavior()
    {
        return $this->behavior;
    }

    public function setBehavior($behavior)
    {
        $this->behavior = $behavior;

        return $this;
    }

    public function getStockOnOrderConfig()
    {
        return $this->stockOnOrderConfig;
    }

    public function setStockOnOrderConfig(StockOnOrderConfig $stockOnOrderConfig)
    {
        $this->stockOnOrderConfig = $stockOnOrderConfig;

        return $this;
    }
}
