<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event\Base;

use Thelia\Core\Event\ActionEvent;
use StockOnOrder\Model\StockOnOrder;

/**
* Class StockOnOrderEvent
* @package StockOnOrder\Event\Base
* @author TheliaStudio
*/
class StockOnOrderEvent extends ActionEvent
{
    protected $id;
    protected $orderId;
    protected $isStockDecreased;
    protected $stockOnOrder;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getOrderId()
    {
        return $this->orderId;
    }

    public function setOrderId($orderId): static
    {
        $this->orderId = $orderId;

        return $this;
    }

    public function getIsStockDecreased()
    {
        return $this->isStockDecreased;
    }

    public function setIsStockDecreased($isStockDecreased): static
    {
        $this->isStockDecreased = $isStockDecreased;

        return $this;
    }

    public function getStockOnOrder()
    {
        return $this->stockOnOrder;
    }

    public function setStockOnOrder(StockOnOrder $stockOnOrder): static
    {
        $this->stockOnOrder = $stockOnOrder;

        return $this;
    }
}
