<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Event\Base;

use StockOnOrder\Event\Module\Base\StockOnOrderEvents as StockOnOrderEventsAlias;
use StockOnOrder\Event\Module\StockOnOrderEvents as ChildStockOnOrderEvents;

/*
 * Class StockOnOrderEvents
 * @package StockOnOrder\Event\Base
 * @author TheliaStudio
 */
class StockOnOrderEvents
{
    const CREATE = StockOnOrderEventsAlias::STOCK_ON_ORDER_CREATE;
    const UPDATE = StockOnOrderEventsAlias::STOCK_ON_ORDER_UPDATE;
    const DELETE = StockOnOrderEventsAlias::STOCK_ON_ORDER_DELETE;
}
