<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use StockOnOrder\Model\StockOnOrderConfigQuery;

/**
 * Class StockOnOrderConfig
 * @package StockOnOrder\Form\Base
 * @author TheliaStudio
 */
class StockOnOrderConfigIdType extends AbstractIdType
{
    const TYPE_NAME = "stock_on_order_config_id";

    protected function getQuery()
    {
        return new StockOnOrderConfigQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
