<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use StockOnOrder\Model\StockOnOrderDecreaseOnCreationQuery;

/**
 * Class StockOnOrderDecreaseOnCreation
 * @package StockOnOrder\Form\Base
 * @author TheliaStudio
 */
class StockOnOrderDecreaseOnCreationIdType extends AbstractIdType
{
    const TYPE_NAME = "stock_on_order_decrease_on_creation_id";

    protected function getQuery()
    {
        return new StockOnOrderDecreaseOnCreationQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
