<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Controller;

use StockOnOrder\Controller\Base\StockOnOrderController as BaseStockOnOrderController;

/**
 * Class StockOnOrderController
 * @package StockOnOrder\Controller
 */
class StockOnOrderController extends BaseStockOnOrderController
{
}
