<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Controller;

use StockOnOrder\Controller\Base\StockOnOrderDecreaseOnCreationController as BaseStockOnOrderDecreaseOnCreationController;

/**
 * Class StockOnOrderDecreaseOnCreationController
 * @package StockOnOrder\Controller
 */
class StockOnOrderDecreaseOnCreationController extends BaseStockOnOrderDecreaseOnCreationController
{
}
