<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action\Base;

use StockOnOrder\Model\Map\StockOnOrderDecreaseOnCreationTableMap;
use StockOnOrder\Event\StockOnOrderDecreaseOnCreationEvent;
use StockOnOrder\Event\StockOnOrderDecreaseOnCreationEvents;
use StockOnOrder\Model\StockOnOrderDecreaseOnCreationQuery;
use StockOnOrder\Model\StockOnOrderDecreaseOnCreation;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class StockOnOrderDecreaseOnCreationAction
 * @package StockOnOrder\Action
 * @author TheliaStudio
 */
class StockOnOrderDecreaseOnCreationAction extends BaseAction implements EventSubscriberInterface
{
    public function create(StockOnOrderDecreaseOnCreationEvent $event)
    {
        $this->createOrUpdate($event, new StockOnOrderDecreaseOnCreation());
    }

    public function update(StockOnOrderDecreaseOnCreationEvent $event)
    {
        $model = $this->getStockOnOrderDecreaseOnCreation($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(StockOnOrderDecreaseOnCreationEvent $event)
    {
        $this->getStockOnOrderDecreaseOnCreation($event)->delete();
    }

    protected function createOrUpdate(StockOnOrderDecreaseOnCreationEvent $event, StockOnOrderDecreaseOnCreation $model)
    {
        $con = Propel::getConnection(StockOnOrderDecreaseOnCreationTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $moduleId = $event->getModuleId()) {
                $model->setModuleId($moduleId);
            }

            if (null !== $decreaseOnOrderCreation = $event->getDecreaseOnOrderCreation()) {
                $model->setDecreaseOnOrderCreation($decreaseOnOrderCreation);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setStockOnOrderDecreaseOnCreation($model);
    }

    protected function getStockOnOrderDecreaseOnCreation(StockOnOrderDecreaseOnCreationEvent $event)
    {
        $model = StockOnOrderDecreaseOnCreationQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'stock_on_order_decrease_on_creation' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            StockOnOrderDecreaseOnCreationEvents::CREATE => array("create", 128),
            StockOnOrderDecreaseOnCreationEvents::UPDATE => array("update", 128),
            StockOnOrderDecreaseOnCreationEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_decrease_on_creation_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_decrease_on_creation_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_decrease_on_creation_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_decrease_on_creation_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
