<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action\Base;

use StockOnOrder\Model\Map\StockOnOrderTableMap;
use StockOnOrder\Event\StockOnOrderEvent;
use StockOnOrder\Event\StockOnOrderEvents;
use StockOnOrder\Model\StockOnOrderQuery;
use StockOnOrder\Model\StockOnOrder;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class StockOnOrderAction
 * @package StockOnOrder\Action
 * @author TheliaStudio
 */
class StockOnOrderAction extends BaseAction implements EventSubscriberInterface
{
    public function create(StockOnOrderEvent $event)
    {
        $this->createOrUpdate($event, new StockOnOrder());
    }

    public function update(StockOnOrderEvent $event)
    {
        $model = $this->getStockOnOrder($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(StockOnOrderEvent $event)
    {
        $this->getStockOnOrder($event)->delete();
    }

    protected function createOrUpdate(StockOnOrderEvent $event, StockOnOrder $model)
    {
        $con = Propel::getConnection(StockOnOrderTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $orderId = $event->getOrderId()) {
                $model->setOrderId($orderId);
            }

            if (null !== $isStockDecreased = $event->getIsStockDecreased()) {
                $model->setIsStockDecreased($isStockDecreased);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setStockOnOrder($model);
    }

    protected function getStockOnOrder(StockOnOrderEvent $event)
    {
        $model = StockOnOrderQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'stock_on_order' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            StockOnOrderEvents::CREATE => array("create", 128),
            StockOnOrderEvents::UPDATE => array("update", 128),
            StockOnOrderEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
