<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StockOnOrder\Action\Base;

use Exception;
use Propel\Runtime\Exception\PropelException;
use StockOnOrder\Event\Base\StockOnOrderConfigEvents as StockOnOrderConfigEventsAlias;
use StockOnOrder\Model\Map\StockOnOrderConfigTableMap;
use StockOnOrder\Event\StockOnOrderConfigEvent;
use StockOnOrder\Model\StockOnOrderConfigQuery;
use StockOnOrder\Model\StockOnOrderConfig;
use Thelia\Action\BaseAction;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use Thelia\Core\Event\TheliaFormEvent;

/**
 * Class StockOnOrderConfigAction
 * @package StockOnOrder\Action
 * @author TheliaStudio
 */
class StockOnOrderConfigAction extends BaseAction implements EventSubscriberInterface
{
    /**
     * @throws Exception
     */
    public function create(StockOnOrderConfigEvent $event): void
    {
        $this->createOrUpdate($event, new StockOnOrderConfig());
    }

    /**
     * @throws Exception
     */
    public function update(StockOnOrderConfigEvent $event): void
    {
        $model = $this->getStockOnOrderConfig($event);

        $this->createOrUpdate($event, $model);
    }

    /**
     * @throws PropelException
     */
    public function delete(StockOnOrderConfigEvent $event): void
    {
        $this->getStockOnOrderConfig($event)->delete();
    }

    /**
     * @throws PropelException
     */
    protected function createOrUpdate(StockOnOrderConfigEvent $event, StockOnOrderConfig $model): void
    {
        $con = Propel::getConnection(StockOnOrderConfigTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $moduleId = $event->getModuleId()) {
                $model->setModuleId($moduleId);
            }

            if (null !== $statusId = $event->getStatusId()) {
                $model->setStatusId($statusId);
            }

            if (null !== $behavior = $event->getBehavior()) {
                $model->setBehavior($behavior);
            }

            $model->save($con);

            $con->commit();
        } catch (Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setStockOnOrderConfig($model);
    }

    protected function getStockOnOrderConfig(StockOnOrderConfigEvent $event)
    {
        $model = StockOnOrderConfigQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'stock_on_order_config' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents(): array
    {
        return array(
            StockOnOrderConfigEventsAlias::CREATE => array("create", 128),
            StockOnOrderConfigEventsAlias::UPDATE => array("update", 128),
            StockOnOrderConfigEventsAlias::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_config_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".stock_on_order_config_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_config_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".stock_on_order_config_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
